---
- name: Ensure Oracle Group exists
  become: true
  ansible.builtin.group:
    name: "{{ wls_os_group }}"
    state: present

- name: Ensure Oracle User exists
  become: true
  ansible.builtin.user:
    name: "{{ wls_os_user }}"
    group: "{{ wls_os_group }}"
    home: "{{ wls_base_dir }}"
    createhome: true
    password: "{{ wls_os_password | password_hash('sha512') }}"
    state: present
    update_password: on_create


